default:
  enabled: false
  duration: 120
  displayName: Рыцари
  description: Убейте своего противника!
  maps:
    - 3

meta:
  horse:
    speed: 0.16875
  weapons:
    - DIAMOND_SPEAR
    - CROSSBOW
    - BOW