default:
  enabled: false
  single: true
  displayName: Казино
  description: Выиграй все деньги в рулетке. Введи в чат свою ставку (красное/черное/зеленое <сумма ставки>).
  maps:
    - 1

meta:
  initialBalance: 10
  goalBalance: 30