default:
  enabled: false
  duration: 120
  displayName: Перелётные снайперы
  description: Застрелите своего противника!
  maps:
    - 1

meta:
  gravity:
    up:
      jumpBoost: 8
      fallBoost: 3